version: "1.1"
services:
  imagestore-server:
    container_name: imagestore-server
    build:
      dockerfile: Dockerfile
    restart: on-failure
    ports:
      - 8080:8080
    networks:
      - imagestore-net
    environment:
      - OTEL_SERVICE_NAME=imagestore-server
      - OTEL_METRICS_EXPORTER=none
      - OTEL_TRACES_EXPORTER=jaeger
      - OTEL_EXPORTER_JAEGER_ENDPOINT=http://jaeger:14250
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysqldb:3306/codecademy?createDatabaseIfNotExist=true&useSSL=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=password
      - FILE_PATH=/var/lib/imagestore/
      - MAX_FILE_SIZE=10485767
      - SERVER_URL=http://localhost:8080
      - SECRET_KEY=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      - JWT_EXP_KEY=3600000
      - REF_TOKEN_EXP=86400000
    volumes:
      - imagestore_data:/var/lib/imagestore
    depends_on:
      - mysqlDB

  mysqldb:
    image: mysql:8.0
    restart: always
    ports:
      - 3306:3306
    networks:
      - imagestore-net
    environment:
      MYSQL_DATABASE: codecademy
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql

  jaeger:
    container_name: jaeger-server
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686"
      - "14250:14250"
    networks:
      - imagestore-net

volumes:
  imagestore_data:
  db_data:

networks:
  imagestore-net:
